version: '3'

services:
  postgres:
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - case_static:/application/static

  aviasales:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    env_file:
      - .env
    volumes:
      - case_static:/application/static

volumes:
  case_static: