# Generated by Django 3.0.4 on 2020-03-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=1024, primary_key=True, serialize=False, unique=True, verbose_name='Слово')),
                ('hash', models.CharField(max_length=64, verbose_name='Хеш-слова')),
            ],
        ),
    ]
